import { z } from "zod";

export type EmployeeFormValues = z.infer<typeof employeeZodSchema>;

export const employeeZodSchema = z.object({
  firstName: z.string().min(2, { message: 'first name must be at least 2 characters' }),
  lastName: z.string().min(2, { message: 'last name must be at least 2 characters' }),
  profilePhoto: z.string().min(2, { message: 'last name must be at least 2 characters' }),
  mobileNumber: z.string().min(2, { message: 'mobile number must be at least 2 characters' }),
  email: z.string().min(2, { message: 'email must be at least 2 characters' }),
  dob: z.string().min(2, { message: 'email must be at least 2 characters' }),
  maritalStatus: z.string().min(2, { message: 'marital status must be at least 2 characters' }),
  gender: z.string().min(2, { message: 'marital status must be at least 2 characters' }),
  nationality: z.string().min(2, { message: 'nationality must be at least 2 characters' }),
  address: z.string().min(2, { message: 'address must be at least 2 characters' }),
  city: z.string().min(2, { message: 'city must be at least 2 characters' }),
  state: z.string().min(2, { message: 'state must be at least 2 characters' }),
  zip: z.string().min(2, { message: 'state must be at least 2 characters' }),
  employeeId: z.string().min(2, { message: 'employee Id must be at least 2 characters' }),
  userName: z.string().min(2, { message: 'user name must be at least 2 characters' }),
  employeeType: z.string().min(2, { message: 'employee type must be at least 2 characters' }),
  department: z.string().min(2, { message: 'department type must be at least 2 characters' }),
  designation: z.string().min(2, { message: 'department type must be at least 2 characters' }),
  workingDays: z.string().min(2, { message: 'working days must be at least 2 characters' }),
  joiningDate: z.string().min(2, { message: 'working days must be at least 2 characters' }),
  officeLocation: z.string().min(2, { message: 'office location must be at least 2 characters' }),
  appointmentLetter: z.string().optional(),
  salarySlips: z.string().optional(),
  relivingLetter: z.string().optional(),
  experienceLetter: z.string().optional(),
  projectName: z.string().min(2, { message: 'office location must be at least 2 characters' }),
  role: z.string().min(2, { message: 'office location must be at least 2 characters' }),
  roleDesignation: z.string().min(2, { message: 'office location must be at least 2 characters' }),
  optionalMessage: z.string().min(2, { message: 'office location must be at least 2 characters' }),
});
