import { TUploadedFile } from "./uploadedFile.type";

/* eslint-disable @typescript-eslint/no-explicit-any */
export type TPayment = {
  id: string;
  projectId: string;
  requestEmployeeId: string;
  title: string;
  description: string;
  amount: number;
  actionByAdminId: string;
  declineReason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  documents?: Partial<TUploadedFile>[];
  createdAt: string;
  updatedAt: string;
  admin: {
    id: string;
    employeeId: string;
    userId: string;
    mobile: string;
    userName: string;
    dob: string;
    maritalStatus: 'SINGLE' | 'MARRIED';
    gender: 'MALE' | 'FEMALE' | 'OTHER';
    employeeType: string;
    department: 'ENGINEERING' | 'MARIN' | 'CIVIL';
    designation: string;
    joiningDate: string;
    officeLocation: string;
    nationality: string;
    street: string;
    city: string;
    state: string;
    zip: number;
    appointmentLetter: string;
    salarySlips: string[];
    relivingLetter: string;
    experienceLetter: string;
    createdProjects: any[];
    createdAt: string;
    updatedAt: string;
    user: {
      id: string;
      firstName: string;
      lastName: string;
      email: string;
      role: string;
    };
  };
  employee: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    role: string;
    engineers?: {
      id: string;
      employeeId: string;
      userId: string;
      mobile: string;
      userName: string;
      dob: string;
      maritalStatus: 'SINGLE' | 'MARRIED';
      gender: 'MALE' | 'FEMALE' | 'OTHER';
      employeeType: string;
      department: 'ENGINEERING' | 'MARIN' | 'CIVIL';
      designation: string;
      joiningDate: string;
      officeLocation: string;
      nationality: string;
      street: string;
      city: string;
      state: string;
      zip: number;
      appointmentLetter: string;
      salarySlips: string[];
      relivingLetter: string;
      experienceLetter: string;
      assignProjects: any[];
      createdAt: string;
      updatedAt: string;
    };
    projectManagers?: {
      id: string;
      employeeId: string;
      userId: string;
      mobile: string;
      userName: string;
      dob: string;
      maritalStatus: 'SINGLE' | 'MARRIED';
      gender: 'MALE' | 'FEMALE' | 'OTHER';
      employeeType: string;
      department: 'ENGINEERING' | 'MARIN' | 'CIVIL';
      designation: string;
      joiningDate: string;
      officeLocation: string;
      nationality: string;
      street: string;
      city: string;
      state: string;
      zip: number;
      appointmentLetter: string;
      salarySlips: string[];
      relivingLetter: string;
      experienceLetter: string;
      assignProjects: any[];
      createdAt: string;
      updatedAt: string;
    };
  };
  project: {
    id: string;
    projectName: string;
    department: 'ENGINEERING' | 'MARIN' | 'CIVIL';
    clientId: string;
    createdBy: string;
    projectManagerId: string;
    startDate: string;
    estimatedEndDate: string;
    projectType: 'ENGINEERING' | 'CIVIL' | 'MARIN';
    productType: 'CIVIL' | 'MARIN' | 'ENGINEERING';
    status: string;
    street: string;
    city: string;
    state: string;
    zip: number;
    createdAt: string;
    updatedAt: string;
  };
};
